# Generated by Django 5.0.3 on 2024-03-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('price', models.CharField(max_length=30, verbose_name='Цена')),
                ('in_stock', models.BooleanField(default=True, verbose_name='в наличии')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
