# Generated by Django 5.0.3 on 2024-03-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0003_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='undefined', max_length=100, verbose_name='Страна'),
        ),
    ]
