# Generated by Django 5.0.3 on 2024-03-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0004_alter_country_options_alter_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
    ]
