# Generated by Django 5.0.3 on 2024-03-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0006_category_photo_product_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
