# Generated by Django 5.0.3 on 2024-03-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0007_delete_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
